/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const { readdirSync } = require('fs');
const capitalize = require('lodash/capitalize');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'LabDAO',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'labdao',
        },
      ],
    },
    {
      type: 'category',
      label: 'mechanism',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'mechanism',
        },
      ],
    },
    {
      type: 'category',
      label: 'Applications',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'applications',
        },
      ],
    },
    {
      type: 'category',
      label: 'community',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'community',
        },
      ],
    },
    {
      type: 'category',
      label: 'projects',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'projects',
        },
      ],
    },
  ],
};

module.exports = sidebars;
